### Obtener todos los workouts
GET http://localhost:3000/api/v1/workouts

### Filtrar workouts por query
GET http://localhost:3000/api/v1/workouts?mode=for

### Crear nuevo workout
POST http://localhost:3000/api/v1/workouts
Content-Type: application/json

{
  "name": "Core Buster",
  "mode": "AMRAP 20",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ],
  "exercises": [
    "15 toes to bars",
    "10 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}

### Obtener workout por id
GET http://localhost:3000/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6

### Actualizar workout existente
PATCH http://localhost:3000/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6
Content-Type: application/json

{
  "name" : "Tommy VI",
  "mode": "Full Time"
}

### Eliminar workout por id
DELETE http://localhost:3000/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6

### Obtener record por id
GET http://localhost:3000/api/v1/workouts/4a3d9aaa-608c-49a7-a004-66305ad4ab50/records